/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 girl.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/girl.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(()=>{
    console.log(actions)
    actions.idle.play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 1.8, 0, .4]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Dress_2_Variant_14_Dress_2_Default_OBJ001" geometry={nodes.Dress_2_Variant_14_Dress_2_Default_OBJ001.geometry} material={materials.NewMat02} skeleton={nodes.Dress_2_Variant_14_Dress_2_Default_OBJ001.skeleton} />
          <skinnedMesh name="Female_Set_1_Boot001" geometry={nodes.Female_Set_1_Boot001.geometry} material={materials.Female_Set_1_Cloth_Boots_} skeleton={nodes.Female_Set_1_Boot001.skeleton} />
          <skinnedMesh name="Female_Set_1_Hand001" geometry={nodes.Female_Set_1_Hand001.geometry} material={materials.Female_Set_1_phong1} skeleton={nodes.Female_Set_1_Hand001.skeleton} />
          <skinnedMesh name="Female_Set_1_Pant001" geometry={nodes.Female_Set_1_Pant001.geometry} material={materials.Female_Set_1_Cloth_Boots_} skeleton={nodes.Female_Set_1_Pant001.skeleton}  />
          <skinnedMesh name="Group19569001" geometry={nodes.Group19569001.geometry} material={materials.Eyeball} skeleton={nodes.Group19569001.skeleton} />
          <skinnedMesh name="Group44842001" geometry={nodes.Group44842001.geometry} material={nodes.Group44842001.material} skeleton={nodes.Group44842001.skeleton} />
          <skinnedMesh name="Group9548001" geometry={nodes.Group9548001.geometry} material={materials.Hair_Mtl} skeleton={nodes.Group9548001.skeleton} />
          <skinnedMesh name="HoodieHeadSub1Group473001" geometry={nodes.HoodieHeadSub1Group473001.geometry} material={materials.Head_Mtl3} skeleton={nodes.HoodieHeadSub1Group473001.skeleton} />
          <skinnedMesh name="HoodieSub3V2Mesh001" geometry={nodes.HoodieSub3V2Mesh001.geometry} material={materials.HoodieMtl} skeleton={nodes.HoodieSub3V2Mesh001.skeleton}  />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/girl.glb')
