/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function OldModel(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Group9548.geometry} material={materials.Hair_Mtl} />
      <mesh geometry={nodes.Group44842.geometry} material={materials.Eyeball} />
      <mesh geometry={nodes.Group19569.geometry} material={materials.Lens} />
      <mesh geometry={nodes.HoodieHeadSub1Group473.geometry} material={materials.Head_Mtl3} />
      <mesh geometry={nodes.HoodieSub3V2Mesh.geometry} material={materials.HoodieMtl} />
    </group>
  )
}

useGLTF.preload('/model.glb')
