/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 NewModel.glb
*/

import React, { useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { useState } from 'react';

export function Model(props) {
  const boxRef = useRef();
  const [rotate, setRotate] = useState(false)

  function rotateModel(){
    setRotate(()=> !rotate);
  }

  useFrame(() => {
  if (rotate == true){
    boxRef.current.rotation.y += 0.003;
  } else {
    boxRef.current.rotation.y = 0;
  }
  });
  const { nodes, materials } = useGLTF('/NewModel.glb')
  return (
    <group {...props} dispose={null} ref={boxRef} onClick >
      <mesh geometry={nodes.Group9548.geometry} material={materials.Hair_Mtl}  />
      <mesh geometry={nodes.Group44842.geometry} material={materials.Eyeball}  />
      <mesh geometry={nodes.Group19569.geometry} material={materials.Eyeball} />
      <mesh geometry={nodes.HoodieHeadSub1Group473.geometry} material={materials.Head_Mtl3}  />
      <mesh geometry={nodes.HoodieSub3V2Mesh.geometry} material={materials.HoodieMtl}/>
    </group>
  )
}

useGLTF.preload('/NewModel.glb')
